# nuPRISMBeamTest WCTE macro with no visualization
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
/hits/verbose 0

###############
# GEOMETRY
###############
/WCSim/WCgeom nuPRISMBeamTest_16cShort_mPMT ## this is 16c4r from CAD
/WCSim/PMT/ReplicaPlacement false
/WCSim/Geometry/SetCDSFile /opt/WCSim/data/Arm_for_Simulation_ASCII_V2.stl
/WCSim/PMT/PositionFile /opt/WCSim/data/mPMT_Position_WCTE_CDS.txt


##################
# AmBe CALIBRATION SOURCE
##################
# if you use ambeevt generator
#/WCSim/BGOPlacement true
#/WCSim/BGOPosition 0 0 0 m

# Set Gadolinium doping (Gd concentration by mass in percent)
#/WCSim/DopingConcentration 0.1
#/WCSim/DopedWater true

/WCSim/Construct

##################
# MISCELLANEOUS
##################

#Added for the PMT QE option 08/17/10 (XQ)
# SensitiveDetector_Only: all the QE are applied at the detector. Good for the low energy running.
# DoNotApplyQE: Switch off the QE, ie. set it at 100%

/WCSim/PMTQEMethod     SensitiveDetector_Only
#/WCSim/PMTQEMethod     DoNotApplyQE

#turn on or off the collection efficiency
/WCSim/PMTCollEff on

# command to choose save neutron capture info
/WCSim/SaveCapture true
# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

##################
# DIGITISER & TRIGGER
##################
#choose the Trigger & Digitizer type (and options)
/DAQ/Digitizer SKI #Uncomment for original
#/DAQ/Trigger NDigits
/DAQ/Trigger NoTrigger #Uncomment for original

#/DAQ/Trigger NDigits
#/DAQ/TriggerNDigits/PreTriggerWindow  -400
#/DAQ/TriggerNDigits/PostTriggerWindow 10000   # ns

# how long does the digitizer integrate for (ns)?
/DAQ/DigitizerOpt/IntegrationWindow 144
#The timing resolution for the digitizer (in ns)
/DAQ/DigitizerOpt/TimingPrecision 0.1

# setseed - option to change seeds
/WCSim/random/seed 20250718

##################
# DARK NOISE
##################
/DarkRate/SetDetectorElement tank
#/DarkRate/SetDarkRate 0 kHz   #Turn dark noise off
/DarkRate/SetDarkRate 1.0 kHz # Default value for 3-inch PMTs in WCTE

# Select which time window(s) to add dark noise to
#/DarkRate/SetDarkMode 0 to add dark noise to a time window starting at
#/DarkRate/SetDarkLow to /DarkRate/SetDarkHigh [time in ns]
#/DarkRate/SetDarkMode 1 adds dark noise hits to a window of
#width /DarkRate/SetDarkWindow [time in ns] around each hit
#i.e. hit time ± (/DarkRate/SetDarkWindow) / 2
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkWindow 4000







/control/alias particle      mu-
/control/alias nEvents       500

/control/alias E             100
/control/alias Eunit         MeV

/control/alias x0            0
/control/alias y0            
/control/alias z0           -1330
/control/alias zTag          zn1200
/control/alias posUnit       mm

/control/alias dx            0
/control/alias dy            0
/control/alias dz            1

/control/alias scatTag       noScat
/control/alias emTag         noE

/control/alias outdir        /eos/user/j/jrimmer/sim_work_dir/WCSim/sim_data

/control/alias energyTag     {E}{Eunit}
/control/alias posTag        x{x0}y{y0}{zTag}
/control/alias runTag        {nEvents}{particle}_{energyTag}_{posTag}_{scatTag}_{emTag}
/control/alias outfile       {runTag}.root

/control/execute /eos/user/j/jrimmer/sim_work_dir/WCSim/WCTE_good.mac
