/WCSim/PMTQEMethod     SensitiveDetector_Only
/WCSim/PMTCollEff on

/WCSim/SavePi0 false
/WCSim/SaveCapture true

/DAQ/Digitizer SKI
#/DAQ/Trigger NDigits
/DAQ/Trigger NoTrigger

/control/execute /opt/WCSim/macros/daq.mac

#/random/setSeeds 2 1
/WCSim/random/seed 596296930


#/DarkRate/SetDarkRate 0 kHz   #Turn dark noise off
/DarkRate/SetDarkRate 1.0 kHz #This is the default value for WCTE PMT.
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkHigh 100000
/DarkRate/SetDarkLow 0
/DarkRate/SetDarkWindow 4000

/mygen/generator gps
/gps/particle gamma
/gps/energy 400.0 MeV
/gps/direction 0 0 1
/gps/position 0 -42.47625 -153.7963 cm
#/gps/ene/type       Lin
#/gps/ene/intercept  1
#/gps/ene/min        0.0 MeV
#/gps/ene/max        2000.0 MeV
#/gps/ang/type       iso
#/gps/pos/type       Volume
#/gps/pos/shape      Cylinder
#/gps/pos/rot1       1 0 0
#/gps/pos/rot2       0 0 1
#/gps/pos/radius     153.7963 cm
#/gps/pos/halfz      135.71175 cm
#/mygen/generator cosmics
#/mygen/cosmicsfile /opt/WCSim/data/WCTE_cosmics.dat

/Tracking/fractionOpticalPhotonsToDraw 0.0

#/WCSimIO/RootFile /mnt/out/wcsim_wCDS_gamma_Beam_200MeV_0cm_0000.root
/WCSimIO/RootFile wcsim.root
/WCSimIO/SaveRooTracker 0

/run/beamOn 200
