# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget WCSimCore WCSimRoot)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target WCSimCore
add_library(WCSimCore SHARED IMPORTED)

set_target_properties(WCSimCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/opt/root/include;/opt/geant4/include/Geant4;/usr/include;/eos/home-j/jrimmer/sim_work_dir/WCSim/include"
  INTERFACE_LINK_LIBRARIES "WCSimRoot;/opt/root/lib/libCore.so;/opt/root/lib/libImt.so;/opt/root/lib/libRIO.so;/opt/root/lib/libNet.so;/opt/root/lib/libHist.so;/opt/root/lib/libGraf.so;/opt/root/lib/libGraf3d.so;/opt/root/lib/libGpad.so;/opt/root/lib/libROOTDataFrame.so;/opt/root/lib/libTree.so;/opt/root/lib/libTreePlayer.so;/opt/root/lib/libRint.so;/opt/root/lib/libPostscript.so;/opt/root/lib/libMatrix.so;/opt/root/lib/libPhysics.so;/opt/root/lib/libMathCore.so;/opt/root/lib/libThread.so;/opt/root/lib/libMultiProc.so;/opt/root/lib/libROOTVecOps.so;G4Tree;G4FR;G4GMocren;G4visHepRep;G4RayTracer;G4VRML;G4OpenGL;G4gl2ps;G4vis_management;G4modeling;G4interfaces;G4persistency;G4analysis;G4error_propagation;G4readout;G4physicslists;G4run;G4event;G4tracking;G4parmodels;G4processes;G4digits_hits;G4track;G4particles;G4geometry;G4materials;G4graphics_reps;G4intercoms;G4global;G4clhep;G4zlib"
)

# Create imported target WCSimRoot
add_library(WCSimRoot SHARED IMPORTED)

set_target_properties(WCSimRoot PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/opt/root/include;/opt/geant4/include/Geant4;/usr/include;/eos/home-j/jrimmer/sim_work_dir/WCSim/include"
  INTERFACE_LINK_LIBRARIES "/opt/root/lib/libCore.so;/opt/root/lib/libImt.so;/opt/root/lib/libRIO.so;/opt/root/lib/libNet.so;/opt/root/lib/libHist.so;/opt/root/lib/libGraf.so;/opt/root/lib/libGraf3d.so;/opt/root/lib/libGpad.so;/opt/root/lib/libROOTDataFrame.so;/opt/root/lib/libTree.so;/opt/root/lib/libTreePlayer.so;/opt/root/lib/libRint.so;/opt/root/lib/libPostscript.so;/opt/root/lib/libMatrix.so;/opt/root/lib/libPhysics.so;/opt/root/lib/libMathCore.so;/opt/root/lib/libThread.so;/opt/root/lib/libMultiProc.so;/opt/root/lib/libROOTVecOps.so;G4Tree;G4FR;G4GMocren;G4visHepRep;G4RayTracer;G4VRML;G4OpenGL;G4gl2ps;G4vis_management;G4modeling;G4interfaces;G4persistency;G4analysis;G4error_propagation;G4readout;G4physicslists;G4run;G4event;G4tracking;G4parmodels;G4processes;G4digits_hits;G4track;G4particles;G4geometry;G4materials;G4graphics_reps;G4intercoms;G4global;G4clhep;G4zlib"
)

# Import target "WCSimCore" for configuration "Release"
set_property(TARGET WCSimCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(WCSimCore PROPERTIES
  IMPORTED_LOCATION_RELEASE "/eos/home-j/jrimmer/sim_work_dir/WCSim/src/src/libWCSimCore.so.1.12.29"
  IMPORTED_SONAME_RELEASE "libWCSimCore.so.1.12.29"
  )

# Import target "WCSimRoot" for configuration "Release"
set_property(TARGET WCSimRoot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(WCSimRoot PROPERTIES
  IMPORTED_LOCATION_RELEASE "/eos/home-j/jrimmer/sim_work_dir/WCSim/src/src/libWCSimRoot.so.1.12.29"
  IMPORTED_SONAME_RELEASE "libWCSimRoot.so.1.12.29"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget WCSimCore WCSimRoot)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target WCSimCore
add_library(WCSimCore SHARED IMPORTED)

set_target_properties(WCSimCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/opt/root/include;/opt/geant4/include/Geant4;/usr/include;/eos/home-j/jrimmer/sim_work_dir/WCSim/include"
  INTERFACE_LINK_LIBRARIES "WCSimRoot;/opt/root/lib/libCore.so;/opt/root/lib/libImt.so;/opt/root/lib/libRIO.so;/opt/root/lib/libNet.so;/opt/root/lib/libHist.so;/opt/root/lib/libGraf.so;/opt/root/lib/libGraf3d.so;/opt/root/lib/libGpad.so;/opt/root/lib/libROOTDataFrame.so;/opt/root/lib/libTree.so;/opt/root/lib/libTreePlayer.so;/opt/root/lib/libRint.so;/opt/root/lib/libPostscript.so;/opt/root/lib/libMatrix.so;/opt/root/lib/libPhysics.so;/opt/root/lib/libMathCore.so;/opt/root/lib/libThread.so;/opt/root/lib/libMultiProc.so;/opt/root/lib/libROOTVecOps.so;G4Tree;G4FR;G4GMocren;G4visHepRep;G4RayTracer;G4VRML;G4OpenGL;G4gl2ps;G4vis_management;G4modeling;G4interfaces;G4persistency;G4analysis;G4error_propagation;G4readout;G4physicslists;G4run;G4event;G4tracking;G4parmodels;G4processes;G4digits_hits;G4track;G4particles;G4geometry;G4materials;G4graphics_reps;G4intercoms;G4global;G4clhep;G4zlib"
)

# Create imported target WCSimRoot
add_library(WCSimRoot SHARED IMPORTED)

set_target_properties(WCSimRoot PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/opt/root/include;/opt/geant4/include/Geant4;/usr/include;/eos/home-j/jrimmer/sim_work_dir/WCSim/include"
  INTERFACE_LINK_LIBRARIES "/opt/root/lib/libCore.so;/opt/root/lib/libImt.so;/opt/root/lib/libRIO.so;/opt/root/lib/libNet.so;/opt/root/lib/libHist.so;/opt/root/lib/libGraf.so;/opt/root/lib/libGraf3d.so;/opt/root/lib/libGpad.so;/opt/root/lib/libROOTDataFrame.so;/opt/root/lib/libTree.so;/opt/root/lib/libTreePlayer.so;/opt/root/lib/libRint.so;/opt/root/lib/libPostscript.so;/opt/root/lib/libMatrix.so;/opt/root/lib/libPhysics.so;/opt/root/lib/libMathCore.so;/opt/root/lib/libThread.so;/opt/root/lib/libMultiProc.so;/opt/root/lib/libROOTVecOps.so;G4Tree;G4FR;G4GMocren;G4visHepRep;G4RayTracer;G4VRML;G4OpenGL;G4gl2ps;G4vis_management;G4modeling;G4interfaces;G4persistency;G4analysis;G4error_propagation;G4readout;G4physicslists;G4run;G4event;G4tracking;G4parmodels;G4processes;G4digits_hits;G4track;G4particles;G4geometry;G4materials;G4graphics_reps;G4intercoms;G4global;G4clhep;G4zlib"
)

# Import target "WCSimCore" for configuration "Release"
set_property(TARGET WCSimCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(WCSimCore PROPERTIES
  IMPORTED_LOCATION_RELEASE "/eos/home-j/jrimmer/sim_work_dir/WCSim/src/src/libWCSimCore.so.1.12.29"
  IMPORTED_SONAME_RELEASE "libWCSimCore.so.1.12.29"
  )

# Import target "WCSimRoot" for configuration "Release"
set_property(TARGET WCSimRoot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(WCSimRoot PROPERTIES
  IMPORTED_LOCATION_RELEASE "/eos/home-j/jrimmer/sim_work_dir/WCSim/src/src/libWCSimRoot.so.1.12.29"
  IMPORTED_SONAME_RELEASE "libWCSimRoot.so.1.12.29"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
